<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{d0f4a2d8-aed2-4597-a76e-704570121f0f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
	//HMI Stuff
	HMI_OUT_Digital 	: ARRAY[0..19] OF BOOL;
	HMI_OUT_Analog 		: ARRAY[0..10] OF INT;
	
	HMI_IN_Digital 		: ARRAY[0..9] OF BOOL;
	HMI_IN_Analog 		: ARRAY[0..19] OF INT;
	
	HMI_IN_Temp 		: ARRAY[0..4] OF REAL;
	
	
	
	//PLC Stuff
	PLC_OUT_Digital 	AT %Q* 		: ARRAY[0..19] OF BOOL;
	PLC_IN_Digital 		AT %I*		: ARRAY[0..9] OF BOOL;
	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>